<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FluxFTP</AssemblyName>
    <Product>FluxFTP</Product>
    <Title>FluxFTP</Title>
    <Version>1.0.58</Version>
    <AssemblyVersion>1.0.58.0</AssemblyVersion>
    <FileVersion>1.0.58.0</FileVersion>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <RootNamespace>IoFtp.Desktop</RootNamespace>
    <ApplicationIcon>Assets\fluxftp-server.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
    <ProjectReference Include="..\IoFtp.Core\IoFtp.Core.csproj" />
    <ProjectReference Include="..\IoFtp.Engine\IoFtp.Engine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\CHANGELOG.md" Link="CHANGELOG.md" />
    <EmbeddedResource Include="..\..\extras\irc\*.mrc;..\..\extras\irc\FluxFTP32.dll;..\..\extras\irc\FluxFTP64.dll;..\..\extras\irc\README.md" LogicalName="FluxFTP.Bridge.irc.%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\..\extras\irc\visionary\*.mrc;..\..\extras\irc\visionary\FluxFTPVisionary32.dll;..\..\extras\irc\visionary\FluxFTPVisionary64.dll;..\..\extras\irc\visionary\README.md" LogicalName="FluxFTP.Bridge.visionary.%(Filename)%(Extension)" />
    <Content Include="..\..\extras\irc\visionary\*.mrc;..\..\extras\irc\visionary\*.dll;..\..\extras\irc\visionary\README.md" Link="extras\irc\visionary\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
    <Content Include="..\..\Rules\_site\*.example" Link="Rules\_site\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
    <Content Include="..\..\Rules\_site\README.md" Link="Rules\_site\README.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>
</Project>
